ci:
  skip: [flutter-analyze, flutter-format]
repos:
  - repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.1
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
      - id: pyupgrade
        args:
          - --py3-plus
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
  - repo: https://github.com/Cretezy/flutter-format-pre-commit
    rev: "4a1df675bb74dea371c17934933e257e46f8dd98"
    hooks:
      - id: flutter-format
        exclude: lib/generated_code
  - repo: https://github.com/dluksza/flutter-analyze-pre-commit
    rev: "0bfdb7415bb2d02794a884bf2b763a92772001eb"
    hooks:
      - id: flutter-analyze
