repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.4
    hooks:
      - id: pyupgrade
        args:
          - --py3-plus
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
