repos:
  - repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.3
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.4
    hooks:
      - id: pyupgrade
        args:
          - --py3-plus
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/Cretezy/dart-format-pre-commit
    rev: "master"
    hooks:
      - id: dart-format
