ci:
  skip: [flutter-analyze, flutter-format]
exclude: 'late.json|.devcontainer/devcontainer.json'
repos:
  - repo: https://github.com/whtsky/pre-commit-pretty-format-json5
    rev: "1.0.0"
    hooks:
      - id: pretty-format-json5
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.3
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
        args:
          - --py3-plus
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
  - repo: https://github.com/Cretezy/flutter-format-pre-commit
    rev: "4a1df675bb74dea371c17934933e257e46f8dd98"
    hooks:
      - id: flutter-format
        exclude: lib/generated_code
  - repo: https://github.com/dluksza/flutter-analyze-pre-commit
    rev: "0bfdb7415bb2d02794a884bf2b763a92772001eb"
    hooks:
      - id: flutter-analyze
