name: transit_dashboard
version: 1.2.3

environment:
  sdk: '>=2.15.0-268.18.beta <3.0.0'

dependencies: 
  json_annotation: ^4.1.0
  sentry: ^6.2.1
  timezone: ^0.8.0
  # awesome_notifications: ^0.6.19
  
dev_dependencies:
  build_runner: 2.0.1
  json_serializable: ^4.1.4
  test: '>=1.15.0 <2.0.0'

