name: newtify
version: 1.2.3

environment:
  sdk: '>=2.12.0 <3.0.0'
  
dependencies: 
  json_annotation: ^4.1.0
  sentry: ^6.2.1
  
dev_dependencies:
  build_runner: 2.0.1
  json_serializable: ^4.1.4
  test: '>=1.15.0 <2.0.0'

