FROM cirrusci/flutter:beta
RUN sudo apt update && sudo apt install fish vim python3-pip --assume-yes
RUN pip3 install pre-commit
# RUN sudo adduser vscode
RUN git config --global user.name "Elliana May"
RUN git config --global user.email "me@mause.me"
