on: push

concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: |
          pip install pipenv
          pipenv install
      - run: pipenv run python main.py

  swagger_validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1.2.1
        with:
          definition-file: lib/swaggers/journey_planner.json

  flutter:
    runs-on: ubuntu-latest
    container: cirrusci/flutter:beta

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Generate sources
        run: flutter pub run build_runner build --verbose

      - name: Analyze project source
        run: flutter analyze

      - run: dart run --define=API_KEY=${{ secrets.API_KEY }} bin/transit_dashboard.dart

      - run: flutter build apk --dart-define=API_KEY=${{ secrets.API_KEY }} --build-number ${{ github.run_number }}

      - name: Verify formatting
        run: flutter format --output=none --set-exit-if-changed .

      - run: mv build/app/outputs/flutter-apk/app-release.apk me.mause.transit_dashboard-1.0.0+${{ github.run_number }}.apk

      - uses: actions/upload-artifact@v2
        with:
          name: apk
          path: '*.apk'

  create_github_release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - flutter
      - swagger_validate
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v2
        with:
          name: apk
          path: '*.apk'

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            *.apk
