on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: |
          pip install pipenv
          pipenv install
      - run: pipenv run python main.py

  dart:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: beta

      - name: Install dependencies
        run: dart pub get

      - name: Generate sources
        run: dart run build_runner build --verbose

      - name: Analyze project source
        run: dart analyze

      - run: dart run --define=API_KEY=${{ secrets.API_KEY }} lib/main.dart

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

  flutter:
    runs-on: ubuntu-latest
    container: cirrusci/flutter:beta

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Generate sources
        run: flutter pub run build_runner build --verbose

      - name: Analyze project source
        run: flutter analyze

      - run: dart run --define=API_KEY=${{ secrets.API_KEY }} lib/main.dart

      - name: Verify formatting
        run: flutter format --output=none --set-exit-if-changed .
