on: push

concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: |
          pip install pipenv
          pipenv install
      - run: pipenv run python main.py
        env:
          REALTIME_API_KEY: ${{ secrets.REALTIME_API_KEY }}

  swagger_validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        definition-file:
          - lib/swaggers/journey_planner.json
          - lib/swaggers/realtime_trip.json

    steps:
      - uses: actions/checkout@v2
      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1.3.1
        with:
          definition-file: ${{ matrix.definition-file }}

  flutter_smoke_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: beta

      - run: flutter update-packages --force-upgrade

      - name: Install dependencies
        run: flutter pub get

      - name: Generate sources
        run: flutter pub run build_runner build --verbose

      - uses: invertase/github-action-dart-analyzer@v1

      - run: |
          dart run \
            --define=REALTIME_API_KEY=${{ secrets.REALTIME_API_KEY }} \
            --define=API_KEY=${{ secrets.API_KEY }} \
            bin/transit_dashboard.dart

  flutter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: beta

      - run: flutter update-packages --force-upgrade

      - name: Install dependencies
        run: flutter pub get

      - name: Generate sources
        run: flutter pub run build_runner build --verbose

      - uses: invertase/github-action-dart-analyzer@v1

      - run: flutter test

      - run: |
          flutter build apk \
            --dart-define=REALTIME_API_KEY=${{ secrets.REALTIME_API_KEY }} \
            --dart-define=API_KEY=${{ secrets.API_KEY }} \
            --dart-define=SENTRY_DSN=${{ secrets.SENTRY_DSN }} \
            --build-number ${{ github.run_number }}

      - name: Verify formatting
        run: flutter format --output=none --set-exit-if-changed .

      - run: mv build/app/outputs/flutter-apk/app-release.apk me.mause.transit_dashboard_${{ github.run_number }}.apk

      - uses: actions/upload-artifact@v2
        with:
          name: apk
          path: '*.apk'

  fastlane:
    runs-on: ubuntu-latest
    needs: [flutter, flutter_smoke_test]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v2
        with:
          name: apk
          path: .
      - run: mv me.mause.transit_dashboard_${{ github.run_number }}.apk transit_dashboard.apk
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.0'
          bundler-cache: true
      - run: ls
      - run: ls transit_dashboard.apk
      - run: bundler exec fastlane test waldo_token:${{ secrets.WALDO_TOKEN }}

  create_github_release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - flutter
      - flutter_smoke_test
      - swagger_validate
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v2
        with:
          name: apk
          path: '*.apk'

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            *.apk
