on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: |
          pip install pipenv
          pipenv install
      - run: pipenv run python main.py

  swagger_validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1.2.1
        with:
          definition-file: lib/swaggers/journey_planner.json

  flutter:
    runs-on: ubuntu-latest
    container: cirrusci/flutter:beta

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Generate sources
        run: flutter pub run build_runner build --verbose

      - name: Analyze project source
        run: flutter analyze

      - run: dart run --define=API_KEY=${{ secrets.API_KEY }} bin/transit_dashboard.dart

      - run: flutter build apk --dart-define=API_KEY=${{ secrets.API_KEY }}

      - name: Verify formatting
        run: flutter format --output=none --set-exit-if-changed .
