on:
  workflow_dispatch:
    inputs:
      dependency:
        required: true
        type: string

name: Update single dependency
jobs:
  update:
    name: Update flutter dependency
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}-${{ hashFiles('pubspec.lock') }}

      - uses: subosito/flutter-action@v2
        with:
          channel: beta

      - run: flutter update-packages --force-upgrade

      - uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: flutter pub upgrade ${{ github.event.inputs.dependency }}
          COMMIT_MESSAGE: "chore: update ${{ github.event.inputs.dependency }}"
          COMMIT_NAME: "GitHub Actions"
          COMMIT_EMAIL: "example@example.com"
          PR_BRANCH_NAME: "update-${{ github.event.inputs.dependency }}"
          PR_TITLE: "chore: update ${{ github.event.inputs.dependency }}"
          PR_BODY: https://pub.dev/packages/${{ github.event.inputs.dependency }}/changelog
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
